    const gameData = {
      gameId: "game-2025-03-27-eidmilanplay21",
      theme: "Eid Milan Play",
      letter_grid: [
        [
          "R",
          "K",
          "S",
          "A",
          "E"
        ],
        [
          "I",
          "P",
          "A",
          "M",
          "T"
        ],
        [
          "Z",
          "E",
          "E",
          "T",
          "E"
        ],
        [
          "A",
          "M",
          "D",
          "I",
          "P"
        ],
        [
          "G",
          "H",
          "I",
          "E",
          "O"
        ],
        [
          "N",
          "U",
          "L",
          "U",
          "I"
        ],
        [
          "T",
          "C",
          "S",
          "T",
          "N"
        ]
      ],
      valid_words: [
        "EIDIHUNT",
        "GAME",
        "CLUE",
        "TASK",
        "PRIZE",
        "TEAM",
        "POINTS"
      ],
      spangram: "EIDIHUNT",
      word_paths: {
        "TASK": [
          [
            2,
            3
          ],
          [
            1,
            2
          ],
          [
            0,
            2
          ],
          [
            0,
            1
          ]
        ],
        "PRIZE": [
          [
            1,
            1
          ],
          [
            0,
            0
          ],
          [
            1,
            0
          ],
          [
            2,
            0
          ],
          [
            2,
            1
          ]
        ],
        "GAME": [
          [
            4,
            0
          ],
          [
            3,
            0
          ],
          [
            3,
            1
          ],
          [
            2,
            2
          ]
        ],
        "EIDIHUNT": [
          [
            2,
            4
          ],
          [
            3,
            3
          ],
          [
            3,
            2
          ],
          [
            4,
            2
          ],
          [
            4,
            1
          ],
          [
            5,
            1
          ],
          [
            5,
            0
          ],
          [
            6,
            0
          ]
        ],
        "CLUE": [
          [
            6,
            1
          ],
          [
            5,
            2
          ],
          [
            5,
            3
          ],
          [
            4,
            3
          ]
        ],
        "TEAM": [
          [
            1,
            4
          ],
          [
            0,
            4
          ],
          [
            0,
            3
          ],
          [
            1,
            3
          ]
        ],
        "POINTS": [
          [
            3,
            4
          ],
          [
            4,
            4
          ],
          [
            5,
            4
          ],
          [
            6,
            4
          ],
          [
            6,
            3
          ],
          [
            6,
            2
          ]
        ]
      }
    };

  export default function handler(req, res) {
    res.status(200).json(gameData);
  }
  
